services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.0
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 16812:16812
      - 16813:16813
      - 16813:16813/udp
    volumes:
      - /mnt/apps/app_data/qbittorrent/appdata:/config
      - /mnt/data/downloads:/downloads
    networks:
      - apps-network
    environment:
      - TZ=Asia/Shanghai
      - WEBUI_PORT=16812
      - TORRENTING_PORT=16813

networks:
  apps-network:
    driver: bridge
    external: true
