services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /apps/postgres/data:/var/lib/postgresql/data
    networks:
      - common-network
    environment:
      POSTGRES_USER: wnanbei
      POSTGRES_PASSWORD: 666888
      POSTGRES_DB: test

networks:
  common-network:
    driver: bridge
    external: true

secrets:
  username:
    file: ./secrets/username
  password:
    file: ./secrets/password
