services:
  mtphotos:
    image: mtphotos/mt-photos:1.33.0
    container_name: mtphotos
    restart: unless-stopped
    env_file: .env
    ports:
      - 16803:8063
    volumes:
      - /mnt/apps/app_data/mtphotos/config:/config
      - /mnt/apps/app_data/mtphotos/upload:/upload
      - /mnt/data/photo:/photo
    networks:
      - apps-network
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${WN_USERNAME}
      - POSTGRES_PASSWORD=${WN_PASSWORD}
      - POSTGRES_DATABASE=mtphotos

  # mt-photos 的场景智能识别服务
  mtphotos-ai:
    image: mtphotos/mt-photos-ai:1.1.0
    container_name: mtphotos-ai
    restart: unless-stopped
    networks:
      - apps-network
    environment:
      - API_AUTH_KEY=${WN_PASSWORD}

  # 人脸识别开源模型
  mtphotos_face_api:
    image: registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:latest
    container_name: mtphotos_face_api
    restart: unless-stopped
    networks:
      - apps-network
    environment:
      - API_AUTH_KEY=${WN_PASSWORD}

networks:
  apps-network:
    driver: bridge
    external: true
