services:
  nextcloud:
    image: nextcloud:30.0.0
    container_name: nextcloud
    restart: unless-stopped
    env_file: .env
    ports:
      - 16801:80
    volumes:
      - /mnt/apps/app_data/nextcloud/data:/var/www/html
    networks:
      - apps-network
    environment:
      NEXTCLOUD_ADMIN_USER: ${WN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${WN_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${WN_USERNAME}
      POSTGRES_PASSWORD: ${WN_PASSWORD}

networks:
  apps-network:
    driver: bridge
    external: true
