services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.11
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "16802:8096"
    volumes:
      - /mnt/apps/app_data/jellyfin/config:/config
      - /mnt/apps/app_data/jellyfin/cache:/cache
      - ./fonts:/usr/local/share/fonts
      - type: bind
        source: /mnt/data/media
        target: /media
    networks:
      - apps-network
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "api.themoviedb.org:99.86.91.26"
      - "api.themoviedb.org:99.86.91.78"
      - "api.themoviedb.org:99.86.91.81"
      - "api.themoviedb.org:99.86.91.93"
      - "api.thetvdb.org:192.241.234.54"
      - "image.tmdb.org:169.150.207.215"

networks:
  apps-network:
    driver: bridge
    external: true
