services:
  mysql:
    image: mysql:8.4.2
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 666888
      MYSQL_USER: wnanbei
      MYSQL_PASSWORD: 666888
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /apps/mysql/data:/var/lib/mysql
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
    external: true
