services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "16820:5432"
    volumes:
      - /mnt/apps/app_data/postgres/data:/var/lib/postgresql/data
    networks:
      - apps-network
    environment:
      POSTGRES_USER: ${WN_USERNAME}
      POSTGRES_PASSWORD: ${WN_PASSWORD}
      POSTGRES_DB: master

networks:
  apps-network:
    driver: bridge
    external: true
