services:
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "16822:6379"
    volumes:
      - /mnt/apps/app_data/redis/data:/data
    networks:
      - apps-network
    command: ["redis-server", "--appendonly", "yes"]

networks:
  apps-network:
    driver: bridge
    external: true
